### ISSUE TITLE
Exclude inspection logs from Endpoint Log View

### ISSUE THREAD

**Issue by zinedkaloc** [cloud-agnost/agnost-community#336]
Currently, Agnost's endpoint logging interface includes logs inspected directly from the navigator, resulting in unnecessary clutter and potential confusion.

### Proposal
To improve the clarity and usability of Agnost's endpoint logs, we suggest implementing a feature to exclude logs inspected from the navigator. This would improve the debugging process by focusing solely on logs generated from actual endpoint interactions.

### Expected Behavior
Logs inspected from the navigator should be excluded from Agnost's endpoint logging, ensuring that only relevant endpoint interaction logs are displayed.

**Comment by umit-yoda** [comment]
We will be adding this feature to our roadmap. To implement this, we also need to complete the filtering of the logs in the log view UI, which is already in progress.

**Comment by umit-yoda** [comment]
We have released the option to filter out logs that are produced when testing the endpoints from Studio. Check out the latest version of Agnost studio.
